fix: add _use/_force_indexes into __copy__ with shallow copy
kayak/pypika pull request #631
Opened 2021-08-29 14:32 UTC by elisong

By #334, #470 , pypika got `force_index`、`use_index` feature, but forgot to add "_force_indexes", "_use_indexes" into `QueryBuilder.__copy__()` with shallow copy, thus they both become mutable. For examples

```python
from pypika import Query

query = Query.from_('customers').select('id', 'fname')
q1 = query.use_index('idx1')
q2 = query
q3 = query.use_index('idx2')

if __name__ == "__main__":
    print(q1.get_sql())
    # SELECT "id","fname" FROM "customers" USE INDEX ("idx1","idx2")
    print(q2.get_sql())
    # SELECT "id","fname" FROM "customers" USE INDEX ("idx1","idx2")
    print(q3.get_sql())
    # SELECT "id","fname" FROM "customers" USE INDEX ("idx1","idx2")
```

2021-08-31 06:58 UTC, x8lucas8x requested changes
@elisong that looks good, but can you please add tests to ImmutabilityTests, so that this can be tested. So far we only have join tests there (i.e. test_queries_after_join). If you could add test cases for other things that are being copied as well (see __copy__), such as selects, groupbys, and so on, that would be great (e.g. test_queries_after_groupby, test_queries_after_select).

2021-08-31 06:59 UTC, x8lucas8x commented
@elisong that looks good, but can you please add tests to ImmutabilityTests, so that this can be tested. So far we only have join tests there (i.e. test_queries_after_join). If you could add test cases for other things that are being copied as well (see __copy__), such as selects, groupbys, and so on, that would be great (e.g. test_queries_after_groupby, test_queries_after_select).

2021-09-02 14:33 UTC, elisong commented
@x8lucas8x Fine, I added some tests.

2021-09-03 11:59 UTC, x8lucas8x commented
@elisong thank you. It looks great now.

2021-09-03 12:01 UTC, merged